

CREATE SEQUENCE teachers_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE rooms
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number INT NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    last_name  VARCHAR(255) NOT NULL,
    birth_date date,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE teachers
(
    id        BIGINT       NOT NULL,
    name      VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    subject   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_teachers PRIMARY KEY (id)
);

ALTER TABLE students
    ADD CONSTRAINT uc_students_lastname UNIQUE (last_name);

ALTER TABLE teachers
    ADD CONSTRAINT uc_teachers_lastname UNIQUE (last_name);